project_id = "tzqllsalkbgdrwooaepd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[storage]
enabled = true
port = 54325
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"

[edge_runtime]
enabled = true
port = 54327

[functions.process-receipt]
verify_jwt = true

[functions.analyze-product]
verify_jwt = true