// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzqllsalkbgdrwooaepd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cWxsc2Fsa2JnZHJ3b29hZXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTgxMDMsImV4cCI6MjA3MjAzNDEwM30.Iehr_7b6CkmK6K5fWztMa9brez6k1HijObfuSWJH528";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});